version: "3"

services:
  api:
    build: DeliveryAPI/
    env_file:
      - .env
    ports:
      - "8001:8001"
  web-form:
    build: WebForm/
    ports:
      - "8000:8000"
  delovye-linii-api:
    build: DelovyeLiniiApi/
  pek-api:
    build: PekApi/